log: debug

cron:
  ttl: "48h"

ssh:
  port: 2222
  identities:
    - "id_ed25519"

http:
  port: 4200
  domain: http://localhost:4200
  log_queries: true
  database:
    dsn: postgres://sdump:sdump@localhost:3432/sdump?sslmode=disable
    log_queries: true

  prometheus:
    username: sdump
    password: sdump
    is_enabled: true
