log: debug

cron:
  ttl: "48h"

ssh:
  port: 2222
  allow_list:
    - ~/.ssh/Lanre.pem
    - ~/.ssh/id_rsa.pub
  identities:
    - "id_ed25519"

http:
  port: 4200
  domain: http://localhost:4200
  rate_limit:
    requests_per_minute: 60
  database:
    dsn: postgres://sdump:sdump@localhost:3432/sdump?sslmode=disable
    log_queries: true

  prometheus:
    username: sdump
    password: sdump
    is_enabled: true
