log: debug

ssh:
  port: 2222

http:
  port: 4200
  domain: https://sdump.app
  database:
    dsn: postgres://sdump:sdump@localhost:3432/sdump?sslmode=disable

  prometheus:
    username: sdump
    password: sdump
