apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-sample
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: sdump
      secretsScope:
        envSlug: prod
        secretsPath: "/"
  managedSecretReference:
    secretName: managed-secret 
    secretNamespace: sdump 
